apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager-webhook-ionos-cloud
  namespace: cert-manager
spec:
  interval: 5m0s
  url: https://ionos-cloud.github.io/cert-manager-webhook-ionos-cloud
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cert-manager-webhook-ionos-cloud
  namespace: cert-manager
spec:
  interval: 5m0s
  chart: cert-manager-webhook-ionos-cloud
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: cert-manager-webhook-ionos-cloud
  version: "*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-ionos-cloud
  namespace: cert-manager
spec:
  interval: 12h
  install:
    createNamespace: false
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chartRef:
    kind: HelmChart
    name: cert-manager-webhook-ionos-cloud
  values: {}
