apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 5m0s
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 5m0s
  chart: tailscale-operator
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: tailscale
  version: "*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 12h
  install:
    createNamespace: false
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chartRef:
    kind: HelmChart
    name: tailscale-operator
  values: {}
