apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/external-dns/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 12h
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chart:
    spec:
      chart: external-dns
      version: "1.20.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 12h
  values:
    image:
      tag: v0.20.0

    # -- ExternalDNS Log level.
    logLevel: debug # reduce in production

    # -- if true, ExternalDNS will run in a namespaced scope (Role and Rolebinding will be namespaced too).
    namespaced: false

    # -- Kubernetes resources to monitor for DNS entries.
    sources:
      - ingress
      - service
      - crd

    policy: sync

    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/mconfalonieri/external-dns-hetzner-webhook
          tag: v0.9.0
          pullPolicy: IfNotPresent
        env:
          # this is a cloud API token
          - name: HETZNER_API_KEY
            valueFrom:
              secretKeyRef:
                name: hetzner-credentials
                key: api-key
          # use the new cloud API
          - name: USE_CLOUD_API
            value: "true"
        livenessProbe:
          httpGet:
            path: /health
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
    
    extraArgs:
      - "--txt-prefix=reg-%{record_type}-"
