---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/external-dns/
---
apiVersion: v1
kind: Secret
metadata:
    name: ionos-credentials
    namespace: external-dns
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:dr5mexzSCnII8J2Eg5NFimL9+TvEikrB9dxcsampUJx1vcRrSw7whkbfA7ALbetWQpUOFkKBdHpaWzMdfzes3903ZXK2dcCjbmx2SdJrkdrXTQu/nW6LNiPUCjZdu31d0HEviAei/TFtzpwpfLyTlb5hBRk=,iv:GlaH0mehwzg7n85o/y4uYyrnYF4yh3fLr/EkUXofqz0=,tag:tn/9M5eiUbsb/qFfrJKsSA==,type:str]
sops:
    lastmodified: "2026-01-18T17:04:10Z"
    mac: ENC[AES256_GCM,data:UXjkg85UdY1ZPZ9ELS5XU+EBozKHvJZNf/FUnGLCHG14a7tfS1YDubpFkV8otRYD+yskuszO2Qkb0SYDOh6XdBkPSN1Ha+v90Rn6/PQRDDxqzlacvP73z4YlguHNVN1RqTwWRD9qt8V8mYqqaRE9xqHSs41alMi+vXI2PPwJZjk=,iv:9FRFEr+RePIOFsqlAgT/0BoBcZ1KhHxc/aevWDq0W4s=,tag:CX9sQe17fGKGw/kcQylqNQ==,type:str]
    pgp:
        - created_at: "2026-01-18T17:04:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4KQPv9+DbRsAQ/+KWdN0uXA3dopGE3Nck1a6WMNIGABjKiCorw18bBJ9ri2
            hl84A0NczqjymvwMRwa/jEBtwl9DG/8o3+QDQw+26yseGNkoxkPMKFah2Q+NtqQu
            KYHlL0ZywVx9Fwgo/Uu0jNmBL0CTk2gNbGxR3btccmtLW4wOD02l0Mp4IMO7VPpd
            rC90Aij+isCL9rmKZXme0Hy9/tM+JRZ2H/zSFmHj99uXHn5eJqdpq3aMJcriSUYD
            K4uFlcl32haz0+LJWqfgQz3XlltZugnUOIUqjB3ocjQzHfR6P2wAw8clWa5zs3AV
            xp3DVuEaqx/YAsvLJsFwYXCzjEJw7trPl1rs+43S8hlQ3xndJj7+P9SCeS83KYPj
            HpzncJdq+ReTmhtI+qzQyrTycc6skL7URA8jL/5nCyI7KloZSycj+qItOGEDuBUh
            Q1l9qAJR3kyLxJOL1ZzwYzqQzxk4s3R9FyGSFJESqfHbEJTkbFndWTkB9daLAupa
            6uInPfB9I5shyjDZjfFiajLMcgnNps6pBF3C+ypAcNj9p4Uk7UKu8xk3uzAYYTbU
            SyqxzSzFNaQ8p4QcwUi2rk7FlguIpnyW73ux/G/DggZUgkka1LFABXo9htpDYhS9
            RDKdjbcku0pkO3NDezL3y2YRNvJLZzusTVJhj65hz/8A4XDPK4CPJjLBKBb7+kvU
            ZgEJAhBBqFhnEyyhrwq+EO5RlFPGEtUWAb/+6ijq06wSYlRdh8FwQ3cToeFDDcoN
            /bUgRAtVaiskuySS0TUYFEsuOJI8zrBQjHpxutFblSm2Ioa5yJubtYXGtTFCbQsi
            j2PnIJUEdA==
            =wEY9
            -----END PGP MESSAGE-----
          fp: CA5041D30E6B1755A06AD223242A7AC1A18F40E8
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 12h
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chart:
    spec:
      chart: external-dns
      version: "1.20.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 12h
  values:
    image:
      tag: v0.20.0

    # -- ExternalDNS Log level.
    logLevel: debug # reduce in production

    # -- if true, ExternalDNS will run in a namespaced scope (Role and Rolebinding will be namespaced too).
    namespaced: false

    # -- Kubernetes resources to monitor for DNS entries.
    sources:
      - ingress
      - service
      - crd

    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/ionos-cloud/external-dns-ionos-webhook
          tag: v0.12.0
          pullPolicy: IfNotPresent
        env:
        - name: LOG_LEVEL
          value: debug # reduce in production
        - name: IONOS_API_KEY
          valueFrom:
            secretKeyRef:
              name: ionos-credentials
              key: api-key
        # The webhook server listens on localhost by default. Otherwise, you can set SERVER_HOST.
        - name: SERVER_PORT
          value: "8888" # default and recommended port for exposing webhook provider EPs
        # The exposed server listens on all interfaces (0.0.0.0) by default. Otherwise, you can set METRICS_HOST.
        - name: METRICS_PORT
          value: "8080" # default and recommended port for exposing metrics and health EPs
        - name: IONOS_DEBUG
          value: "true" # change to "true" if you want see details of the http requests
        - name: DRY_RUN
          value: "true" # set to "false" when you want to allow making changes to your DNS resources
