apiVersion: v1
kind: Secret
metadata:
    name: ionos-credentials
    namespace: external-dns
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:7glEIYYDwffqSu8JyXDBekRRWLmU2cZbtgWCspxWun0r8w2exUZtHe/QGQGGzFOE4zxHid/d8Cupx9FQWaLjkzu/I8qEBS3B7kqMsvRRCZU74nOHB5NWtne8w31Ev9G4yILpQ9rny2lAjTyQo8cfznL7fmoA2YKfPG2vTWZ4mofTPErkZd8rc7EmcpcrZLm2lBR3FmE=,iv:Q9M9eFdMp3Yk70HMVE21Vwr9cDQ5/W2U7A51/f74v6Y=,tag:IQ0xrXHtR74Jp00csbkbTw==,type:str]
sops:
    lastmodified: "2026-01-18T17:15:01Z"
    mac: ENC[AES256_GCM,data:uLR3Jprfz5dLGaV49eHrKqG2RC3ilnrM97Hl387qb/O7ud1blQCjemrJ4xKnzS0zmJ/Ze+R3D2O1auAG2W1Br3iNrr8jTgzJlKC+jeyQ9QHjwhk+HGs6gBWUDLP7ct1xPME1I7oDl/upl8Y/4Glr7URFOWYskXdtJhjJaRc7OwU=,iv:FXxPNpDmEgUXPEM7rNlVJBC4alhNmbERhwr75nli0zc=,tag:f8pPCuUs1qWI02KWr5l+sw==,type:str]
    pgp:
        - created_at: "2026-01-18T17:15:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4KQPv9+DbRsARAApXy0XeJ9C42YC5tCLeNxb1D6fgn0M8rI/hxtIl9LU0/+
            UMCrig1JSAx9OP3q081dSI/LBOmIrZ+wuyL8P5XFRuoKUJf2ma2k+8i/B6GD+g45
            a8g5KEXv1IAN3gS1/TSCsdSnXdy4JWLqOgXPa3ZZblJ7063yzcKqtoZip9lnvLFI
            r1tyxR6a3Sw6l9OJJzB5Zv/GxwDqlwqf3ifbthr51tQoSog6akuh4fh5PcbXG5T+
            DX3t/CC9dmakFs+ptqQ6434fsEoh/z02dpKtFcxH/Rc78VhVmFSXbdCdoTJLkca4
            qCHO/AsuE1gYww9TPRHYZ/k7+bjYaDMEC7P204+r9C0Z6GgZqK+GrYL9bzzv2UvG
            XIYVkFWISld9HuRktmIb7SFLTyk3QdLscdplBd0WU6kRHhRfastTs7zqLy3NXgYL
            0DxCbY27aeLPhqZp58hVWpNznSRnwIpGqU4YXLfWeA9sA6TknKmmXG4W+1R4WRUc
            2nU2xghxHZhm5bi+7XvcyL3InM+iExEDltVmnuvaEkhGGsOKH7bUbkQ/h3gm9KjK
            ZiX1HZx//HzVTJ0iFt6eRpUb/TpJjX2OOoNKblqOii9uGfxgoAG+kzmdCkRUx/O2
            Wy/NKpUPd9jDqL/ZoccY9ZT9vHQH1/57TCQauho0wO6KHYo1+q180rj3/m/uiZPU
            aAEJAhAmBAxOU0jqPzbrbrAkSOZZ3NuDWzw+KpTYMEMU7HjKf5uRKg/P+n6sKBQj
            eazdNYszUPU+GI2/y2l1QqSMWjsi35ATdbDFsQgLWt3K45JnKJa6bQITDjD0AwNh
            tNzNjPYzK3aW
            =3kl+
            -----END PGP MESSAGE-----
          fp: CA5041D30E6B1755A06AD223242A7AC1A18F40E8
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
