apiVersion: v1
kind: Secret
metadata:
    name: ionos-credentials
    namespace: external-dns
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:q1SC74qXBIR29v57tt2M11AVMGSw4ZK3hRc3k84fBm345ogi/p4sQ1pD0m+5zu7rgoamH/EwIi04SOkRs2lsHjQIRoEBvd7pPfbBRZXuFfpah/jd2tZqn/7Y2cc5JZQ3PSZVIH/PgDCh84iTz0qxxjByBMcRS/uriTpnRlEEg3f+O378DWbzJRDsA36IW2keVfy6WYc=,iv:sGlnhzjfSEmDk6MebQBfs3IRWjhtCyYCCJeI59DxCQ4=,tag:ELvcUEeV7HT5Z6i+uPD2AQ==,type:str]
sops:
    lastmodified: "2026-01-18T17:14:03Z"
    mac: ENC[AES256_GCM,data:TpZgqLelMue82+YMloqaeV/e72CZwZYle88GYcVhMFBHtRFPPTxWyl1O7+cQJauGpvR4p08eQL3rU6x4aGOR7HLtosyIWJUECBRLgo+2p7/yDs4khAGfqcL28e7NsnbICe9WVPZ0PXNhKA8rK5QWgsdJu0TXVBJ1u4CU4L20K5A=,iv:mchf8F5HPPTiE0GgXvIRykdada0meNzQ2vNRRmGKZXM=,tag:wPjFtMJkWEUEL5WK/NPn0g==,type:str]
    pgp:
        - created_at: "2026-01-18T17:14:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4KQPv9+DbRsAQ//QzML7aER2AdGIfvyXJzVDmydJQDE9EC8ZFlA1bz+F14O
            Rw6c1EDBXyjBUS2Lb8U8rqba8/NTajyNF3FYWYb06/tF6jPse5FfAvSB9FpPeV1s
            k+I2raFilgfjJz7yjuniWSppS0TfAIQT9a5V0OZRvRPDqs/RyN0eu2QXwtbdfZyy
            BW6i3VsaRqtY3+eXmXnoTvJfs3d8WRXqxkyHxT7HnG81CF8Dmx+MHopXIk8n8bFA
            /sd398jQMg+N4t4FgoDNkbqGDfutMwSg9TTxVgs/U84y/EKcmHHWX1wPBMvm1ATo
            0RNdBhU1tR31pF6iNcJ678luYwPc2hcvUZ//3rUb4lW2GpqLRjn0J1qR2PtGZYu9
            T2RUBpvmd+RxwjyjXMX1mdsHv3oE7SgnQArtPgazbHPQ6vy9OYQXK+TB0VzXIu3+
            9zM5W33WJKs2/wpklFO1jFJpgoVuOrjpoIQftulEKYt93vuSIU07933LgRuxGMQK
            a3vTchAsP7hrfqJjAjkluLm1enfoOEVZLWQxZ7HTmm8l5c9vGnKet6y9JhZCIGit
            YmYz5VXY8rVEcS0mGV4ckwsBR+0skTEKrwQIJgUCzi2TnL23p0HChfyoBBJByo0c
            8QUCROJqCIOvqQbFZTQt3DZIK3VoJNagFukkZrWgxxAGVhspWg9ZXldwtCb9AqnU
            ZgEJAhDIVLr4DCwM+oXCGkdvLx8eHqdsSLi0j3vm6QoopqffCEsr5Ppi3j+1g5wo
            cmfoTatumcVtUTY2bX5J2a0TOFquYL2ct9bdv1u4BVlgUtXFxAYFs/Ek0yHh3BeY
            m5a1nm/U9Q==
            =0m00
            -----END PGP MESSAGE-----
          fp: CA5041D30E6B1755A06AD223242A7AC1A18F40E8
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
