apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc
  namespace: pihole
  labels:
    app: pihole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-etc
  namespace: pihole
  labels:
    app: pihole
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/pihole/etc
    type: DirectoryOrCreate
  claimRef:
    name: pihole-etc
    namespace: pihole
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - alderaan
