apiVersion: apps/v1
kind: Deployment
metadata:
  name: matter-server
  namespace: home-assistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: matter-server
  template:
    metadata:
      labels:
        app: matter-server
    spec:
      hostNetwork: true
      # this init conainer is needed to set the correct permissions on the data volume
      initContainers:
        - name: configure-permissions
          image: busybox
          # the user and group id used by matterjs-server is 1000:1000, see its Dockerfile
          command: ["sh", "-c", "chown -R 1000:1000 /data"]
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: matter-server
          image: ghcr.io/matter-js/matterjs-server:1.4.0
          securityContext:
            privileged: true
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName:
              home-assistant-matter-v2
      # prevent two matter-server pods from being scheduled at a time, only one instance should be running
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - matter-server
            topologyKey: "kubernetes.io/hostname"
