apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: local-storage
