apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-time
  namespace: home-assistant
  labels:
    app: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-time
  namespace: home-assistant
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /etc/localtime
  claimRef:
    name: home-assistant-time
    namespace: home-assistant
