apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-matter
  namespace: home-assistant
  labels:
    app: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Mi
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-matter
  namespace: home-assistant
  labels:
    app: home-assistant
spec:
  capacity:
    storage: 32Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/home-assistant/matter
    type: DirectoryOrCreate
  claimRef:
    name: home-assistant-matter
    namespace: home-assistant
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - alderaan
