apiVersion: batch/v1
kind: CronJob
metadata:
  name: paperless-export-sync
  namespace: paperless-ngx
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: paperless-export
              image: mbentley/nextcloud-client:latest
              env:
                - name: NEXTCLOUD_URL
                  valueFrom:
                    secretKeyRef:
                      name: nextcloud-credentials
                      key: url
                - name: USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: nextcloud-credentials
                      key: username
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: nextcloud-credentials
                      key: password
                - name: OPTIONS
                  value: "--non-interactive --path /paperless/export"
              volumeMounts:
                - name: export
                  mountPath: /data
          volumes:
            - name: export
              persistentVolumeClaim:
                claimName: paperless-ngx-export
          restartPolicy: OnFailure
