apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: export-trigger
  namespace: paperless-ngx
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "create"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
