apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: export-trigger
  namespace: paperless-ngx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: export-trigger
subjects:
  - kind: ServiceAccount
    name: export-trigger
    namespace: paperless-ngx
