apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-sync
  namespace: paperless-ngx
  labels:
    app: paperless-ngx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-ngx-sync
  namespace: paperless-ngx
  labels:
    app: paperless-ngx
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/paperless-ngx/sync
  claimRef:
    name: paperless-ngx-sync
    namespace: paperless-ngx
