apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-hole-etc
  namespace: pi-hole
  labels:
    app: pi-hole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pi-hole-etc
  namespace: pi-hole
  labels:
    app: pi-hole
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/pi-hole/etc
    type: DirectoryOrCreate
  claimRef:
    name: pi-hole-etc
    namespace: pi-hole
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - alderaan
